"""Data loading utilities for the Proteomics Clinical Index Engine.

These helpers keep notebook code lightweight and make data assumptions explicit.
The demo repository uses synthetic Olink-style NPX data, but the same schema
checks can be adapted for vendor-exported NPX CSV/Parquet/Excel files.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable, Tuple

import pandas as pd


REQUIRED_NPX_COLUMNS = {
    "SampleID",
    "OlinkID",
    "UniProt",
    "Assay",
    "Panel",
    "NPX",
    "LOD",
    "QC_Warning",
    "PlateID",
    "SampleQC",
    "BelowLOD",
    "MissingFreq",
}

REQUIRED_METADATA_COLUMNS = {
    "SampleID",
    "SubjectID",
    "Age",
    "Sex",
    "BMI",
    "DiseaseStatus",
    "WHO_Severity",
    "SevereOutcome",
    "CollectionDay",
    "PlateID",
    "SampleQC",
}


def project_root() -> Path:
    """Return repository root assuming this file lives under src/proteomics_index."""
    return Path(__file__).resolve().parents[2]


def _read_table(path: str | Path) -> pd.DataFrame:
    """Read CSV, TSV, Parquet, or Excel into a pandas DataFrame."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Data file not found: {path}")

    suffix = path.suffix.lower()
    if suffix == ".csv":
        return pd.read_csv(path)
    if suffix in {".tsv", ".txt"}:
        return pd.read_csv(path, sep="	")
    if suffix == ".parquet":
        return pd.read_parquet(path)
    if suffix in {".xlsx", ".xls"}:
        return pd.read_excel(path)
    raise ValueError(f"Unsupported file type: {suffix}. Use CSV, TSV, Parquet, or Excel.")


def validate_columns(df: pd.DataFrame, required: Iterable[str], table_name: str) -> None:
    """Raise a clear error if a DataFrame is missing required columns."""
    missing = sorted(set(required) - set(df.columns))
    if missing:
        raise ValueError(f"{table_name} is missing required columns: {missing}")


def load_npx_data(path: str | Path) -> pd.DataFrame:
    """Load and validate long-format Olink-style NPX data."""
    df = _read_table(path)
    validate_columns(df, REQUIRED_NPX_COLUMNS, "NPX table")

    # Normalise expected dtypes where possible.
    df = df.copy()
    df["SampleID"] = df["SampleID"].astype(str)
    df["Assay"] = df["Assay"].astype(str)
    df["NPX"] = pd.to_numeric(df["NPX"], errors="coerce")
    df["LOD"] = pd.to_numeric(df["LOD"], errors="coerce")
    df["BelowLOD"] = df["BelowLOD"].astype(bool)
    return df


def load_metadata(path: str | Path) -> pd.DataFrame:
    """Load and validate sample-level metadata."""
    df = _read_table(path)
    validate_columns(df, REQUIRED_METADATA_COLUMNS, "Metadata table")
    df = df.copy()
    df["SampleID"] = df["SampleID"].astype(str)
    df["SevereOutcome"] = pd.to_numeric(df["SevereOutcome"], errors="raise").astype(int)
    return df


def load_sample_project_data(root: str | Path | None = None) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Load the synthetic demo NPX and metadata tables shipped with the repo."""
    root = Path(root) if root is not None else project_root()
    npx_path = root / "data" / "sample" / "olink_synthetic_npx.csv"
    metadata_path = root / "data" / "sample" / "sample_metadata.csv"
    return load_npx_data(npx_path), load_metadata(metadata_path)


def check_duplicate_measurements(npx: pd.DataFrame) -> pd.DataFrame:
    """Return duplicate SampleID-Assay measurements, if any."""
    validate_columns(npx, {"SampleID", "Assay"}, "NPX table")
    mask = npx.duplicated(subset=["SampleID", "Assay"], keep=False)
    return npx.loc[mask].sort_values(["SampleID", "Assay"])


def pivot_npx_to_matrix(
    npx: pd.DataFrame,
    value_col: str = "NPX",
    sample_col: str = "SampleID",
    feature_col: str = "Assay",
) -> pd.DataFrame:
    """Convert long-format NPX data into a sample-by-protein ML matrix."""
    validate_columns(npx, {sample_col, feature_col, value_col}, "NPX table")
    duplicates = npx.duplicated(subset=[sample_col, feature_col], keep=False)
    if duplicates.any():
        raise ValueError(
            "Duplicate sample-feature measurements found. Resolve duplicates before pivoting."
        )

    matrix = npx.pivot(index=sample_col, columns=feature_col, values=value_col)
    matrix = matrix.sort_index(axis=0).sort_index(axis=1)
    matrix.index.name = sample_col
    return matrix


def load_processed_matrix(root: str | Path | None = None) -> Tuple[pd.DataFrame, pd.Series, pd.DataFrame]:
    """Load processed X, y, and metadata files generated by the notebooks."""
    root = Path(root) if root is not None else project_root()
    X = pd.read_csv(root / "data" / "processed" / "X_proteomics.csv", index_col=0)
    y_df = pd.read_csv(root / "data" / "processed" / "y_severe_outcome.csv")
    metadata = pd.read_csv(root / "data" / "processed" / "metadata_model.csv")

    if "SevereOutcome" in y_df.columns:
        y = y_df["SevereOutcome"]
    else:
        y = y_df.iloc[:, -1]
    return X, y, metadata


def align_matrix_metadata(X: pd.DataFrame, metadata: pd.DataFrame, sample_col: str = "SampleID") -> pd.DataFrame:
    """Return metadata aligned to the row order of an ML matrix."""
    if sample_col not in metadata.columns:
        raise ValueError(f"Metadata must contain {sample_col}")
    missing = set(X.index.astype(str)) - set(metadata[sample_col].astype(str))
    if missing:
        raise ValueError(f"Metadata missing {len(missing)} samples represented in X")
    aligned = metadata.set_index(sample_col).loc[X.index.astype(str)].reset_index()
    return aligned
